py# Generated by Django 4.1.5 on 2023-02-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(default='noncategory', max_length=128),
        ),
    ]
